name: Lint and TypeScript Check

on:
  pull_request:
    branches:
      - '**'  # Run on pull requests for all branches
  push:
    branches:
      - '**'  # Run on push for all branches
  workflow_dispatch:  # Allow manual triggering

jobs:
  lint-and-ts-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Use Node.js version 18

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run TypeScript check
        run: npm run build
